package.json
=> chore: add lint and format:check scripts

.github/workflows/ci.yml, src/rules/assertion-type.test.ts, src/rules/lower-case-title.test.ts, src/rules/no-conditional-in-tests.test.ts, src/rules/no-skipped-tests.test.ts
=> chore: improves CI and added lint job

.github/workflows/release.yml
=> feat: add release workflow

README.md
Adding a list of all supported rules to the README.
N/A
=> docs: add a list of rules to README

README.md, src/rules/no-conditional-tests.test.ts, src/rules/no-conditional-tests.ts
=> no-conditional in tests

README.md, src/index.ts, src/rules/expect-expect.test.ts, src/rules/expect-expect.ts, src/rules/no-conditional-tests.ts
=> Expect expect

src/rules/expect-expect.ts
=> fix expect-expect rule

src/rules/expect-expect.test.ts, src/rules/expect-expect.ts
=> feat: make meeting links private

src/rules/lower-case-title.ts, src/rules/max-nested-describe.ts, src/rules/no-conditional-tests.test.ts, src/rules/no-conditional-tests.ts, src/rules/no-identical-title.ts
=> chore: fixing no-conditional tests

README.md, docs/rules/max-nested-describe.md, src/rules/max-nested-describe.ts, src/rules/no-conditional-tests.ts
=> feat: fix max describe blocks

README.md, docs/rules/no-hooks.md, src/index.ts, src/rules/no-hooks.test.ts, src/rules/no-hooks.ts, src/utils/parseVitestFnCall.ts
=> feat: no-hooks rule

src/index.ts
=> Add vitest globals

README.md, docs/rules/no-restricted-vi-methods.md, src/index.ts, src/rules/no-restricted-vi-methods.test.ts, src/rules/no-restricted-vi-methods.ts, src/utils/parseVitestFnCall.ts
=> feat: no-restricted-vi-method rule

src/rules/no-skipped-tests.test.ts, src/rules/no-skipped-tests.ts
=> no-skipped-tests

README.md, docs/rules/consistent-test-filename.md, src/index.ts, src/rules/consistent-test-filename.test.ts, src/rules/consistent-test-filename.ts
=> add rule `vitest/consistent-test-filename`

README.md, docs/rules/consistent-test-filename.md, src/index.ts, src/rules/consistent-test-filename.ts
=> add default opt to `consistent-test-filename`

README.md, docs/rules/prefer-strict-equal.md, src/index.ts, src/rules/prefer-strict-equal.test.ts, src/rules/prefer-strict-equal.ts
=> prefer-strict-equal

README.md, docs/rules/preferMockPromiseShorthand.md, src/index.ts, src/rules/prefer-mock-promise-shorthand.test.ts, src/rules/prefer-mock-promise-shorthand.ts
=> prefer-mock-promise-shorthand

src/rules/prefer-called-with.ts
=> fix(prefer-called-with): support toHaveBeenCalledOnce

docs/rules/valid-title.md, package.json, pnpm-lock.yaml, src/rules/valid-title.test.ts, src/rules/valid-title.ts
=> feat: allow passing arguments as title

docs/rules/prefer-lowercase-title.md, src/rules/prefer-lowercase-title.test.ts, src/rules/prefer-lowercase-title.ts
=> feat(prefer-lowercase-title): introduce lowercaseFirstCharacterOnly option

README.md, docs/rules/prefer-called-with.md, fixtures/package.json, package.json, pnpm-lock.yaml, src/rules/prefer-called-with.test.ts, src/rules/prefer-called-with.ts
=> feat: add autoFix to prefer-called-with

docs/rules/consistent-test-it.md
=> Replace jest/consistent-test-it with vitest/consistent-test-it in example code

README.md, docs/rules/expect-expect.md
=> chore: update docs

src/rules/prefer-lowercase-title.ts, src/utils/parseVitestFnCall.ts, src/utils/types.ts, tests/prefer-lowercase-title.test.ts
=> feat(bench): prefer lowercase title for bench

package.json, pnpm-lock.yaml
=> chore: remove typescript from dependencies

fixtures/package.json, package.json, pnpm-lock.yaml
=> chore: update packages

fixtures/package.json, package.json, pnpm-lock.yaml
=> chore(deps): update dependencies

tests/expect-expect.test.ts
=> chore(trying to fix expect): expect-expect

src/rules/valid-describe-callback.ts, tests/valid-describe-callback.test.ts
=> fix(false positive): stop false positive 

package.json, pnpm-lock.yaml
=> feat(deps): updated dependancies

src/index.ts
A "hello world" string was logged to console in the index.ts. I removed it.
=> Remove "hello world" log

fixtures/.eslintrc, fixtures/.eslintrc.json, fixtures/index.test.ts, fixtures/package.json, fixtures/pnpm-lock.yaml, package.json, pnpm-lock.yaml, src/rules/expect-expect.ts, tests/expect-expect.test.ts
=> fix(bench): avoid bench being recognized by expect-expect rule

fixtures/package.json, fixtures/pnpm-lock.yaml, fixtures/tests/conditional.test.ts
=> fix(fixtures): update fixtures

package.json, pnpm-lock.yaml
=> chore(update deps): update dependancies

fixtures/package.json, fixtures/pnpm-lock.yaml, src/index.ts
=> fix(missing-key): vitest plugin key

package.json, pnpm-lock.yaml, src/index.ts
=> chore(legacy): add support for legacy configs

package.json, pnpm-lock.yaml
=> feat: revert package update

docs/rules/valid-title.md
=> chore(typo): fixed typo in valid-title.md

package.json, pnpm-lock.yaml
=> improve peer deps

docs/rules/no-focused-tests.md
This PR makes a minor improvement to `no-focused-tests.md`.
=> docs: minor improvement to no-focused-tests.md

src/rules/consistent-test-it.ts, src/rules/padding-around-after-all-blocks.ts, src/utils/index.ts
=> fix(build): fix build

src/rules/expect-expect.ts, tests/expect-expect.test.ts
=> fix(expect-expect): make assert work well with expect-expect

tests/expect-expect.test.ts
improve test case basing on #495
=> improve tests

src/rules/valid-expect.ts, src/utils/parse-vitest-fn-call.ts, src/utils/types.ts, tests/valid-expect.test.ts
=> [valid-expect] Support typecheck

README.md, docs/rules/valid-expect-in-promise.md, src/index.ts, src/rules/valid-expect.ts
- Added documentation for the valid-expect-in-promise rule.
- Minor refactoring: removed unused variables and fixed typos.
=> docs: Add Documentation for valid-expect-in-promise Rule

src/rules/valid-expect.ts, src/utils/parse-vitest-fn-call.ts, src/utils/types.ts, tests/valid-expect.test.ts
=> fix false postive issues

package.json, src/rules/no-done-callback.ts, src/rules/prefer-spy-on.ts, src/rules/prefer-to-be-object.ts, src/rules/require-local-test-context-for-concurrent-snapshots.ts, src/rules/valid-expect.ts, unbuild.config.ts
=> fix: various build issues

package.json
=> fix: remove the `module-sync` condition

src/rules/require-mock-type-parameters.ts, tests/require-mock-type-parameters.test.ts
=> fix(require-mock-type-parameters): fixed checking of type annotation

src/index.ts
=> Add recommended and all configs to base plugin

src/rules/valid-title.ts, tests/valid-title.test.ts
=> fix(valid-title): also allow string types with settings.typecheck

src/rules/prefer-describe-function-title.ts
=> chore: fix prefer-describe-function-title

package.json, pnpm-lock.yaml
=> chore: fix dependancies

src/index.ts, src/utils/types.ts, tests/valid-title.test.ts
=> fix(valid-title): Please allow function-typed variables and aliases as valid describe titles

.prettierignore, src/index.ts
=> chore: fix  import inclusivity

docs/rules/warn-test.md, src/index.ts, src/rules/warn-todo.ts, tests/warn-todo.test.ts
=> feat: New rule `warn-todo`

docs/rules/prefer-expect-type-of.md, src/index.ts, src/rules/prefer-expect-type-of.ts, tests/prefer-expect-type-of.test.ts
Closes [#741](https://github.com/vitest-dev/eslint-plugin-vitest/issues/741)
=> feat: prefer expectTypeOf
