vitest-dev/eslint-plugin-vitest

- README.md
- src/index.ts
- src/rules/no-focused-tests.test.ts
- src/rules/no-focused-tests.ts
---
Adds a new `no-focused-tests` rule (similar to [Jest's](https://github.com/jest-community/eslint-plugin-jest/blob/main/src/rules/no-focused-tests.ts)). It's essentially a copy/paste of the `no-skipped-tests` rule, but it looks for `.only` instead of `.skip`.
> Add new `no-focused-tests` rule

- README.md
- docs/rules/assertion-type.md
- docs/rules/expect-expect.md
- docs/rules/lower-case-title.md
- docs/rules/max-nested-describe.md
- docs/rules/no-conditional-tests.md
- docs/rules/no-focused-tests.md
- docs/rules/no-identical-title.md
- docs/rules/no-skipped-tests.md
- package.json
- pnpm-lock.yaml
This PR fixes/implements the following ~**bugs/features**~ docs!
Fixes #15
Aligns very closely to the setup description from https://github.com/bmish/eslint-doc-generator, just without `markdownlint`.
> docs: onboarded to eslint-doc-generator

- src/rules/no-focused-tests.test.ts
- src/rules/no-focused-tests.ts
Addresses this comment https://github.com/veritem/eslint-plugin-vitest/pull/9#issuecomment-1359371437
The user has correctly reported that the current `no-focused-tests` rule is highlighting the entire test case as a failure. After this PR only the `only` keyword will be highlighted as a failure.
Also updates the unit test to capture this requirement.
> feat: highlight only keyword in no-focused-tests rule

- .github/workflows/smoke-test.yml
- .gitignore
- eslint-remote-tester.config.ts
- package.json
- pnpm-lock.yaml
Adds weekly scheduled smoke tests to be run on every Sunday at 00:00. Tests can also be trigger manually (`workflow_dispatch`). These tests will be looking for rule crashes.
Some example ESLint community plugins that are using this tool already:
- `eslint-plugin-react`
- `eslint-plugin-jest`
- `eslint-plugin-jest-extended`
- `eslint-plugin-jest-dom`
- `eslint-plugin-testing-library`
- `eslint-plugin-unicorn`
Helps finding issues like below even before releasing:
- https://github.com/veritem/eslint-plugin-vitest/issues/27
- https://github.com/veritem/eslint-plugin-vitest/issues/21
- https://github.com/veritem/eslint-plugin-vitest/issues/20
Here is the first run: https://github.com/AriPerkkio/eslint-plugin-vitest/issues/1
> Detected …
> test: adds weekly scheduled smoke tests

- README.md
- src/rules/no-done-callback.ts
follow up #155
The following error was shown when running `pnpm lint`:
> Please run eslint-doc-generator. A rule doc is out-of-date: docs\rules\no-done-callback.md
> docs: fix typo

- src/rules/no-focused-tests.test.ts
- src/rules/no-focused-tests.ts
This PR enhances no-focussed-tests a bit.
I noticed the `no-focused-tests` rule doesn't apply if you have an `only` on an `it.each`. This adds a check to report an error if an `it.only.each` or `describe.only.each` is encountered.
I also noticed this rule will report on `it.only` and `describe.only`, but not `test.only`, so I added an extra check for that. 
I love this plugin, thanks for the hard work!
> Small no-focussed-tests updates

- README.md
- docs/rules/prefer-mock-promise-shorthand.md
- src/rules/prefer-mock-promise-shorthand.ts
Other rules uses kebab case but only this rule was using camel case.
This PR changes the rule name to kebab case for consistency.
---
BTW thank you for creating/porting this much rules!
> chore!: rename `preferMockPromiseShorthand` rule to `prefer-mock-promise-shorthand`

- .github/workflows/smoke-test.yml
- Fixes #243
- Fixes #241
The `||=` operator is not supported in Node 14. This PR updates `eslint-remote-tester-run-action` to v4 which runs on Node 18: https://github.com/AriPerkkio/eslint-remote-tester-run-action/releases/tag/v4
> fix: smoke tests to use node 18

- src/rules/consistent-test-it.ts
- tests/consistent-test-it.test.ts
When using explicit import from `vitest`, rewriting only `test()` to `it()` will cause the `test` not found error, and requires manually updating the imported named. This PR make it auto-fix as well.
> feat(consistent-test-it): rewrite import statement as well

- src/rules/no-disabled-tests.ts
- tests/no-disabled-tests.test.ts
- tests/prefer-lowercase-title.test.ts
> feat(no-disabled-tests): make error ranges smaller

- README.md
- docs/rules/unbound-method.md
- src/index.ts
- tests/unbound-method.test.ts
Support for the `unbound-method` rule has been added in [#207](https://github.com/veritem/eslint-plugin-vitest/pull/207), but the rule was not exported, so it couldn't be used:
```
Definition for rule 'vitest/unbound-method' was not found. [vitest/unbound-method]
```
I assumed this was unintentional, since [the original issue about `unbound-method`](https://github.com/veritem/eslint-plugin-vitest/issues/171) was marked "Fixed" in the PR's description.
In this PR I uncommented the relevant lines, and completed the docs with info from the [`eslint-plugin-jest`](https://github.com/jest-community/eslint-plugin-jest/blob/main/docs/rules/unbound-method.md#requires-type-checking) repo.
Thank you for your work on this repo, and let me know if I have to change something! ☺️
> fix: export the "unbound-method" rule

- README.md
- docs/rules/unbound-method.md
- src/index.ts
- tests/unbound-method.test.ts
Reverts veritem/eslint-plugin-vitest#286
> Revert "fix: export the "unbound-method" rule"

- src/rules/expect-expect.ts
This is inspired by a fix that was recently merged into `eslint-plugin-jest` https://github.com/jest-community/eslint-plugin-jest/pull/1452 and released in 27.4.3 https://github.com/jest-community/eslint-plugin-jest/releases/tag/v27.4.3
When writing tests (I often encounter this with Testing Library) where I do a large amount of setup / querying before I get to my first expectation my editor is essentially screaming at me for a while. I find this to be overly noisy where in reality I just want to make sure I don't commit an empty test case with this rule.
After this change, it instead only highlights the test identifier itself, which is much less distracting:
> [expect-expect] Report of test identifier rather than body

- src/rules/no-done-callback.ts
- tests/no-done-callback.test.ts
> fix(vitest/no-done-callback): do not report accessing of text context when test runs concurrently

- docs/rules/require-local-test-context-for-concurrent-snapshots.md
- src/index.ts
- src/rules/require-local-test-context-for-concurrent-snapshots.ts
- tests/require-local-test-context-for-concurrent-snapshots.test.ts
I added a new rule. It forces the use of the local Test Context in snapshot tests that run in parallel. For more background, see #311.
This change improves the developer experience. It tells the developer that the test will fail while writing it. Without this rule the developer will find that out when test runs.
To test the new rule you can execute the unit test. Or you clone the repo, activate the rule and insert the code snippet below:
```js
import { describe, expect, it } from 'vitest';
describe.concurrent('something', () => {
it('should report', () => {
expect(true).toMatchInlineSnapshot('1');
});
it('should not report', (context) => {
context.expect(true).toMatchSnapshot();
});
});
it.concurrent('should report', () => {
expect(1).toMatchInlineSnapshot();
});
it('should not report', …
```
> feat(vitest/require-local-test-context-for-concurrent-snapshots): add rule

- README.md
- docs/rules/no-import-node-test.md
- src/index.ts
- src/rules/no-import-node-test.ts
- tests/no-import-node-test.test.ts
It was so annoying to me that VS Code often auto inserts the import from `node:test` when I type `describe` or `test`. It's might also hard to spot and found the bug. I think when ppl using Vitest, they are very unlikely to use `node:test` together. Having this rule allow the import to `node:test` always been fixed to `vitest`
> feat: new rule `no-import-node-test`

- docs/rules/no-done-callback.md
- src/rules/no-done-callback.ts
- tests/no-done-callback.test.ts
I updated the rule to no report when the local Test Context is used inside a test that is inside a concurrent describe block. 
The current implementation reported a false-positive when the scenario described above exists. 
The rule goes up its ancestors and checks if it's inside a concurrent test or describe block.
You can run the unit tests to check if the rule works. To check that on your local machine:
1. Active the rule (`vitest/no-done-callback`) 
2. Copy the following code snippet.
```js
import { describe, it } from 'vitest'; 
describe.concurrent('something', () => {
it('something', ({ context }) => {
expect(1).toBe(1);
});
});
```
You will not see any linting error as long as the describe block has its `.concurrent` annotation. Once that gets removed the error will appear.
> fix(vitest/no-done-callback): do not report when inside concurrent describe

- src/rules/require-local-test-context-for-concurrent-snapshots.ts
- tests/require-local-test-context-for-concurrent-snapshots.test.ts
The rule now reports any invalid snapshot assertion in concurrent tests. That is when they don't use the local Test Context
It's required to use the local Test Context for every single type of snapshot tests.
I expanded the criteria for what is a snapshot assertion and what is not.
Run the unit tests to verify the new expected result. Follow these steps if you want to test it on your local machine:
Activate the rule `vitest/require-local-test-context-for-all-types-of-snapshot-tests`
Copy the code snippet below
```js
import { describe, expect } from 'vitest';
describe.concurrent("something", () => {
it("something", () => {
expect(() => {
throw new Error('foo')
}).toThrowErrorMatchingInlineSnapshot();
});
it("something", () => {
expect("foo").toMatchFileSnapshot("./bar.txt");
});
}); …
```
> fix(vitest/require-local-test-context-for-concurrent-snapshots): report for all types of snapshot tests

- docs/rules/expect-expect.md
- fixtures/.eslintrc
- fixtures/index.test.ts
- fixtures/pnpm-lock.yaml
- src/index.ts
- src/rules/expect-expect.ts
- tests/expect-expect.test.ts
- tests/prefer-expect-assertions.test.ts
> Feat/expect expect issues 

- docs/rules/valid-title.md
In the `valid-title` rule docs, it was not clear how to set specific matchers for `describe`, `tests` and `it` titles.
I added some examples in the docs of the rule.
Let me know if I missed some things.
> docs(valid-title-rule): elaborate valid-title rule properties docs

- README.md
- docs/rules/expect-expect.md
- src/rules/expect-expect.ts
- src/utils/parsePluginSettings.ts
- tests/expect-expect.test.ts
As type-checking can be enabled via `--typecheck` or `typecheck.enabled` in `vitest.config.ts`, it felt better to make this an opt-in - like the type-testing feature is.
With this approach, other rules can also handle type-testing with the new setting.
Fixes #382.
> feat: add support for expectTypeOf to expect-expect

- src/rules/consistent-test-filename.ts
- src/rules/expect-expect.ts
- src/rules/no-commented-out-tests.ts
- src/rules/no-conditional-expect.ts
- src/rules/no-done-callback.ts
- src/rules/no-large-snapshots.ts
- src/rules/no-test-return-statement.ts
- src/rules/prefer-comparison-matcher.ts
- src/rules/prefer-equality-matcher.ts
- src/rules/prefer-mock-promise-shorthand.ts
- src/rules/prefer-spy-on.ts
- src/rules/prefer-to-contain.ts
- src/rules/require-local-test-context-for-concurrent-snapshots.ts
- src/utils/index.ts
Fixes #413 by replacing all the `context` methods which have been deprecated in eslint v8, and subsequently removed in v9 or are slated for removal in v10 (outlined in [this blog post](https://eslint.org/blog/2023/09/preparing-custom-rules-eslint-v9/#main)). 
The supported `eslint` versions all have the new syntax: 
https://github.com/veritem/eslint-plugin-vitest/blob/76f00f604308e3ad3cd5fe3bdd302a1262b6ee1f/package.json#L70
Therefore it's safe to use the replacement methods directly, without a fallback to the old methods (which they showcase in the blog post for backwards compatibility).
> fix(rules): replace `context` deprecations

- docs/rules/no-focused-tests.md
- src/rules/no-focused-tests.ts
- tests/no-focused-tests.test.ts
Adds autofix to focused tests to eliminate the `only`. The autofix can be disabled by passing `false` to the `fixable` option. This should maybe be reversed, so it isn't enabled by default, but rather an opt-in?
> feat(no-focused-tests): add autofix

- src/index.ts
Fixes #427 
This also fixes the globals values of `env` config. It was previously `writeable` but the correct is `writable` (all though I don't understand why it's specified as writable in the first place). This was not type checked previously since there are no type constraints with `Object.assign`.
Side note: I'm noticing that the CI pipeline don't typecheck the code. `pnpm tsc` fails on main for me.
> fix: configs in plugin declaration file

- package.json
- src/index.ts
- src/rules/padding-around-after-all-blocks.ts
- src/rules/padding-around-after-each-blocks.ts
- src/rules/padding-around-all.ts
- src/rules/padding-around-before-all-blocks.ts
- src/rules/padding-around-before-each-blocks.ts
- src/rules/padding-around-describe-blocks.ts
- src/rules/padding-around-expect-groups.ts
- src/rules/padding-around-test-blocks.ts
- src/utils/ast-utils.ts
- src/utils/msc.ts
- src/utils/padding.ts
- tests/padding-around-after-all-blocks.test.ts
- tests/padding-around-after-each-blocks.test.ts
- tests/padding-around-all.test.ts
- tests/padding-around-before-all-blocks.test.ts
- tests/padding-around-before-each-blocks.test.ts
- tests/padding-around-describe-blocks.test.ts
- tests/padding-around-expect-groups.test.ts
- tests/padding-around-test-blocks.test.ts
> formating rules port 

- src/utils/ast-utils.ts
There's `require.resolve()` call in `.mjs` file. 
https://github.com/veritem/eslint-plugin-vitest/blob/d74b09b552372daeb8f2f1d1583c1a194bd1f210/src/utils/ast-utils.ts#L4
Ran into this issue while fixing other problem in the codebase.
```bash
$ pnpm build; node dist/index.mjs 
> eslint-plugin-vitest@0.6.0 build /<root>/eslint-plugin-vitest
> unbuild
ℹ Automatically detected entries: src/index [esm] [cjs] [dts]            3:33:18 PM
ℹ Building eslint-plugin-vitest                                          3:33:18 PM
ℹ Cleaning dist directory: ./dist                                        3:33:18 PM
✔ Build succeeded for eslint-plugin-vitest                               3:33:20 PM
[3:33:20 PM]   dist/index.cjs (total size: 192 kB, chunk size: 192 kB, exports: default)
[3:33:20 PM] …
```
> fix: `require` in ESM

- .github/workflows/ci.yml
- .github/workflows/smoke-test.yml
- eslint-remote-tester.config.ts
- package.json
- pnpm-lock.yaml
- src/utils/ast-utils.ts
Continues work from https://github.com/veritem/eslint-plugin-vitest/pull/470, with fix applied from https://github.com/veritem/eslint-plugin-vitest/pull/473.
Example run: https://github.com/AriPerkkio/eslint-plugin-vitest/actions/runs/9482770552/job/26128361215
- chore: set `packageManager`
- Lockfile seems to be generated with `pnpm@9`, but CIs are using `pnpm@8`
- Contributors may end up re-generating whole lockfile if the version doesn't match with expected major
- test: fix smoke tests
- Run tests against 10K repositories from `eslint-remote-tester-repositories`, instead of just a single one
- Use required peer dependency `eslint@9` - the Node API of `eslint@8` is not compatible with required version 9. I wonder why there's no warning from `peerDependencies` conflict 🤔
> test: fix smoke tests

- src/rules/no-disabled-tests.ts
When people encounter this error they don't know they still have the option to use `.todo()` instead of `.skip()` and they end up removing code that might be useful.
> Update error message of no-disabled-tests rule

- src/rules/consistent-test-it.ts
- tests/consistent-test-it.test.ts
This PR fixes so that `bench` doesn't get recognized by the `consistent-test-it` rule.
> fix(bench): avoid bench being recognized consistent-test-it rule

- docs/rules/prefer-expect-resolves.md
Fixes #
Removed the redundant code block start (` ``` `) which caused GitHub to add an empty code block at the end of the markdown preview in <ins>prefer-expect-resolves.md</ins>.
> Improved The Documentation

- src/rules/expect-expect.ts
- tests/expect-expect.test.ts
Fixes a false positive when using the 'extend' features of the test context. This is my first commit to the eslint plugin system so let me know if I've gotten anything wrong about how to approach the tests etc.
> Avoid test.extend in expect-expect throwing a false positive.

- package.json
- pnpm-lock.yaml
- src/utils/padding.ts
👋 Hi! Coming over from https://github.com/typescript-eslint/typescript-eslint/issues/9501: we're working on typescript-eslint v8 and would like to try the beta out on plugins such as `eslint-plugin-vitest`.
I'm sending this draft PR as a reference to see what issues we might give you in upgrading and to try to be helpful. If this is annoying noise to you, please forgive me, I'll withdraw the PR. But I hope this is useful on your end - and please let me know if you have any feedback! ❤️
> chore: bump typescript-eslint to v8

- README.md
- src/index.ts
Adding `"extends": ["plugin:vitest/legacy-recommended"]` to your `.eslintrc` results in:
> ESLint couldn't find the plugin "eslint-plugin-vitest".
Once switched to `plugin:@vitest/legacy-recommended` the error persists because `createConfigLegacy` itself has the value `plugins: ['vitest']`.
After fixing that you will get errors like:
> error  Definition for rule 'vitest/prefer-to-be' was not found
This is fixed by correcting the rule name prefix in `createConfigLegacy`.
> Fix legacy rules for new @vitest/eslint-plugin package

- README.md
this PR fixes the instructions for the plugin name.
the current instructions
```
plugins: ['@vitest']
```
give this error when running `npm run lint` in a package:
```
Oops! Something went wrong! :(
ESLint: 9.8.0
ESLint couldn't find the plugin "eslint-plugin-vitest".
(The package "eslint-plugin-vitest" was not found when loaded as a Node module from the directory "/Users/yair/p/vite-app-template".)
It's likely that the plugin isn't installed correctly. Try reinstalling by running the following:
npm install eslint-plugin-vitest@latest --save-dev
...
```
> fixed instructions for legacy plugin name

- docs/rules/valid-describe-callback.md
- src/rules/valid-describe-callback.ts
- tests/valid-describe-callback.test.ts
vitest allow to use `async` in `describe`'s callback.
This PR just remove `noAsyncDescribeCallback` error.
fix #511
> fix(valid-describe-callback): remove `noAsyncDescribeCallback`

- docs/rules/valid-expect.md
- src/rules/valid-expect.ts
- tests/valid-expect.test.ts
Allow to use `expect(value, "message").toBe(1)` pattern.
📝 Note: TypeScript type information is required for accurate implementation.
Since ASTs may not contain type, only simple string literals and template literals are supported.
OK:
```js
expect(value, "string literal").toBe(1);
expect(value, `template literal`).toBe(1);
const message = "message";
expect(value, `${message}`).toBe(1);
```
NG:
```js
// variable is not allowed - it is limitation of current implemtation
const message = "message";
expect(value, message).toBe(1);
// non string types
expect(value, {}).toBe(1);
expect(value, []).toBe(1);
expect(value, 1).toBe(1);
```
This feature is undocument yet, but `vitest` type definition define it.
- https://github.com/vitest-dev/vitest/issues/6337
Waiting until it is documented may be …
> fix(valid-expect): allow `expect(value, "message")`

- src/rules/padding-around-after-all-blocks.ts
- src/rules/padding-around-after-each-blocks.ts
- src/rules/padding-around-all.ts
- src/rules/padding-around-before-all-blocks.ts
- src/rules/padding-around-before-each-blocks.ts
- src/rules/padding-around-describe-blocks.ts
- src/rules/padding-around-expect-groups.ts
- src/rules/padding-around-test-blocks.ts
- src/utils/msc.ts
Previously, `dist/*` can not define correct `RULE_NAME` in some rules.
This PR use hard code `RULE_NAME` instead of `getFilename` util
1. replace `getFilename` with `<filename>`
2. remove `getFilename` usage
```bash
#!/bin/bash
for file in $(ls -1 src/rules/*.ts); do
echo "Processing $file"
sed -i '' -e "s#getFilename(import.meta.url)#'$(basename ${file%.*})'#g" $file
done
```
fix #509
> fix: fix formatting rules name

- README.md
> docs: Use valid plugin name in ESLint v8 instructions

- src/rules/prefer-lowercase-title.ts
When `lowercaseFirstCharacterOnly` is turned off, the error message needs to be changed.
By the way, I think changing this option to ‘fullyLowercaseCharacter’ might be more intuitive. Users set this value because they want all lowercase characters.
> fix: correct the message when required to be all lowercase

- src/rules/expect-expect.ts
- tests/expect-expect.test.ts
Also push `assertType` to the allowed `assertFunctionNames` in `expect-expect` rule when typecheck is enabled in the settings. 
fix #533.
> fix: add 'assertType' to 'expect-expect' allowed assertions

- package.json
This makes this plugin easier to consume when it's installed as part of a shared config, in case `vitest` is not installed by the host.
See also: https://github.com/jest-community/eslint-plugin-jest/pull/970
> fix: Make `vitest` peer dependency optional

- src/rules/expect-expect.ts
`items: [{ type: 'string' }]` is not a valid JSON schema option.
> Wrong JSON schema for expect-expect

- src/index.ts
- src/rules/valid-expect-in-promise.ts
- tests/valid-expect-in-promise.test.ts
Adapted from [jest/valid-expect-in-promise](https://github.com/jest-community/eslint-plugin-jest/blob/main/src/rules/__tests__/valid-expect-in-promise.test.ts).
This is the only rule I'm missing after migrating from jest, so it'd be nice to have it in order to depend only on @vitest/eslint-plugin .
> feat(vitest/valid-expect-in-promise): add rule

- src/rules/valid-expect-in-promise.ts
> fix: __filename is not defined in ES module scope when using eslint.config.mjs

- README.md
- docs/rules/valid-expect.md
- src/rules/valid-expect.ts
- tests/valid-expect.test.ts
> [valid-expect] include fixer for adding missing await

- docs/rules/valid-describe-callback.md
- src/rules/valid-describe-callback.ts
- tests/valid-describe-callback.test.ts
> [valid-describe-callback] Fix to support options as second parameter for valid-describe-callback

- src/rules/prefer-expect-assertions.ts
- src/rules/require-local-test-context-for-concurrent-snapshots.ts
- src/utils/parse-vitest-fn-call.ts
- tests/prefer-expect-assertions.test.ts
> fix: expect.hasAssertions() / expect.assertions() - Does not work when using expect() bound to current test

- src/index.ts
Hello, the globals defined in @vitest/eslint-plugin ([source](https://github.com/vitest-dev/eslint-plugin-vitest/blob/main/src/index.ts#L269-L285)) are not synchronized with the official type definitions in vitest/globals.d.ts ([source](https://github.com/vitest-dev/vitest/blob/main/packages/vitest/globals.d.ts)).
close https://github.com/vitest-dev/eslint-plugin-vitest/issues/598
> feat: add missing globals 

- src/rules/prefer-expect-assertions.ts
- src/utils/parse-vitest-fn-call.ts
- tests/prefer-expect-assertions.test.ts
I included an additional fix for a similar false negative in another case of #567.
> [prefer-expect-assertions]fix false negatives for test context usage

- src/rules/expect-expect.ts
- tests/expect-expect.test.ts
Fixes expectation detection in call chains when one member contains an underscore.
For instance
```
it('should pass', () => {
any_chain.to.expect(true)
})
```
Does not currently pass, whereas the following does pass
```
it('should pass', () => {
anyChain.to.expect(true)
})
```
> fix: detect expectations in chains with underscores

- docs/rules/no-standalone-expect.md
Fix `no-standalone-expect` docs example option to include severity.
> docs: fix no-standalone-expect.md options example

- src/rules/expect-expect.ts
For performance reason, only parse patterns and create RegExp once instead of doing it for each tested node.
> perf: only build regexp once for detecting expectations

- src/index.ts
- src/utils/index.ts
- tests/expect-expect.test.ts
- tests/unbound-method.test.ts
- tsconfig.json
I have made the following changes:
- Fixed type errors in the test files.
- Updated `plugin.config`. Reference: [eslint-plugin-jest](https://github.com/jest-community/eslint-plugin-jest/blob/main/src/index.ts).
There may be some misunderstandings on my part, but I would appreciate your review.
> Refactor tsconfig for Stricter Type-Safe Settings

- src/rules/valid-title.ts
- tests/valid-title.test.ts
> fix: `valid-title` false positives when `test.extend` is used

- src/rules/consistent-test-filename.ts
- src/rules/max-expects.ts
- src/rules/max-nested-describe.ts
- src/rules/no-commented-out-tests.ts
- src/rules/no-conditional-tests.ts
- src/rules/no-disabled-tests.ts
- src/rules/no-duplicate-hooks.ts
- src/rules/no-focused-tests.ts
- src/rules/no-mocks-import.ts
- src/rules/no-test-prefixes.ts
- src/rules/prefer-to-be-object.ts
- src/rules/require-top-level-describe.ts
- src/rules/valid-expect.ts
- src/rules/valid-title.ts
I noticed a spelling mistake in `valid-expect` that I'd fixed in `eslint-plugin-jest` which revealed https://github.com/jest-community/eslint-plugin-jest/pull/1444 has not been ported over, so this mostly does that though also has a few other adjustments.
There's some more improvements that could be made which I don't mind doing (namely around the use of code quotes), but didn't want to do too much without first confirming folks are happy with this kind of "format" 🙂
> fix: make rule message punctuation more consistent and address some typos

- src/index.ts
This PR changes the `VitestPlugin` type to use a non nullish `configs` value, as it makes the type easier to use in type aware configs.
It probably broke as part of this commit:
- https://github.com/vitest-dev/eslint-plugin-vitest/commit/5f1aac92cd9fd4aac35ab14e15a0b1cc3b29236a#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80R169
Ref:
- https://github.com/faker-js/faker/pull/3358
> chore: avoid nullish config type

- src/index.ts
- src/rules/consistent-test-it.ts
- src/utils/index.ts
- tests/consistent-test-it.test.ts
Fixed to also remove duplicate imports inside the import statement during the fix, as per the PR title.
> fix(consistent-test-it): Remove duplicate imports inside the import statement

- src/index.ts
- src/rules/prefer-strict-boolean-matchers.ts
- tests/prefer-strict-boolean-matchers.test.ts
I am explicitly not reporting for `.toEqual(true)` or `.toStrictEqual(true)`, there's already `prefer-to-be` for that.
Closes #639
> feat: added the `prefer-strict-boolean-matchers` rule

- .github/workflows/ci.yml
- package.json
- pnpm-lock.yaml
- src/index.ts
- src/rules/require-mock-type-parameters.ts
- src/utils/index.ts
- unbuild.config.ts
Fixed to run typecheck in CI.
Notes were commented in the code.
Fixed the following to make typecheck succeed.
- Fixed to use Typescript-eslint's Rule type.
- Added @ts-expect-error to suppress type errors.
- Edited package.json so that the correct version of `@typescript-eslint/utils` is installed.
> use typescript eslint rule type

- src/rules/consistent-test-filename.ts
- tests/consistent-test-filename.test.ts
closes https://github.com/vitest-dev/eslint-plugin-vitest/issues/673
> fix(consistent-test-filename): match allTestPattern against full file path

- docs/rules/valid-title.md
I fixed the allowArguments option in valid-title.
> docs: fix allowArguments in valid-title

- src/index.ts
> feat: add `name` property to configs

- docs/rules/valid-title.md
- src/rules/valid-title.ts
- tests/valid-title.test.ts
Fixes: #687 
Also updates the sample code in the documentation.
> fix(valid-title): report emptyTitle for string-like types

- .github/workflows/ci.yml
- eslint.config.js
- package.json
- src/rules/no-test-prefixes.ts
Running `pnpm lint:js` generates small issues, which leads to eslint plugin in vscode or other editors not working properly. - This is fixed with first commit.
Additionally to ensure upcoming issues, adding the the `pnpm lint:js` job to the CI might be a good way, to prevent. To achieve that, I changed the `pnpm lint:js` to not fix anymore, just check. To run the fix locally it could be achieved by running: `pnpm lint:js --fix`.
> Fix "lint:js" Job and extend CI proposal

- .github/workflows/ci.yml
- src/index.ts
- src/rules/require-mock-type-parameters.ts
- src/utils/index.ts
- tests/no-importing-vitest-globals.test.ts
- tests/prefer-importing-vitest-globals.test.ts
With this PR the `pnpm tsc` should succeed and can be activated in CI, if suits. I hope I didn't break any other things, but you'll find my way below:
So I went on reading into https://typescript-eslint.io/developers/custom-rules and changed `createEslintRule` accordingly. Then went on to https://github.com/typescript-eslint/examples/blob/main/packages/eslint-plugin-example-typed-linting/src/index.ts and changed return types in plugin accordingly.
Rest of the tsc issues (in tests) where just "hidden" due to tsc wasn't checked in CI - fixed them accordingly.
Hope this makes the changes understandable, I am happy to hear, also if I missed something.
> Proposal to fix "pnpm tsc"

- src/rules/prefer-importing-vitest-globals.ts
- tests/prefer-importing-vitest-globals.test.ts
Fix false positives in `prefer-importing-vitest-globals` rule.
The `prefer-importing-vitest-globals` rule was incorrectly flagging local variables, function parameters, and other local bindings that happened to have the same name as vitest globals (like `test`, `describe`, `it`, etc.).
For example, this code would incorrectly trigger the rule:
```ts
import { describe, expect, it } from 'vitest'
describe('test suite', () => {
it('should work', () => {
let test = createTestWithParameters(3) // Rule incorrectly flagged this
expect(test()).toBeTruthy()
})
})
```
I encountered an issue in my project:
https://github.com/azat-io/eslint-plugin-de-morgan/blob/main/test/utils/create-test-with-parameters.test.ts
Added proper scope analysis to distinguish between:
- Local bindings (variables, …
> fix(prefer-importing-vitest-globals): ignore local vars with vitest global names

- src/rules/prefer-expect-assertions.ts
- tests/prefer-expect-assertions.test.ts
```ts
it("it1", () => {
expect.assertions(0);
const foo = { bar({ baz }) { baz(); } };
});
```
`members` is an empty array [here](https://github.com/vitest-dev/eslint-plugin-vitest/blob/b44c039d47fd77b001262f97d8349e2cb2c4101b/src/rules/prefer-expect-assertions.ts#L205-L206).
```
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Failed Tests 1 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
FAIL  tests/prefer-expect-assertions.test.ts > prefer-expect-assertions > valid > it("it1", () => {
expect.assertions(0);
const foo = { bar({ baz }) { baz(); } };
});
Error: Caught an error while linting
❯ Linter.linter.verify node_modules/.pnpm/@typescript-eslint+rule-tester@8.24.1_eslint@9.20.0_jiti@2.4.2__typescript@5.7.3/node_modules/@typescript-eslint/rule-tester/src/RuleTester.ts:239:19
❯ …
```
> Repair parse error in `vitest/prefer-expect-assertions`

- docs/rules/require-mock-type-parameters.md
Fix the incorrect rule name in the vitest/require-mock-type-parameters example in the docs
> fix(docs): fix incorrect rule name in vitest/require-mock-type-parameters example

- src/rules/prefer-describe-function-title.ts
- tests/prefer-describe-function-title.test.ts
close: https://github.com/vitest-dev/eslint-plugin-vitest/issues/743
> feat(prefer-describe-function-title): Check for unnecessary .name

- src/rules/require-top-level-describe.ts
- tests/require-top-level-describe.test.ts
Allows usage of `test.extend()` on top level.
I can also make it work with additional configuration flag if needed.
> require-top-level-describe: allow test context extend

- src/utils/parse-vitest-fn-call.ts
- tests/max-expects.test.ts
- tests/valid-title.test.ts
- Fixes `max-expects` when test function is created with test context
- Fixes empty title for `valid-title` rule with test context (no particular changes, the fix to max-expects highlighted the issue it the tests)
> max-expects: fix when test context is used
